### PR TITLE
Fix displaying unbalanced comments

### PR DESCRIPTION
**Pull request by kant2002**
When comment ends with `**)` or with more stars
trigger everything into comment after myself

### CODE REVIEW

**Comment by baronfel** [comment]
Hello, thanks for your interest. Would you mind a screenshot for before/after this change?

@MangelMaxime would you mind taking a look?

**Comment by kant2002** [comment]
# Before 
image

This one produced with current version of Ionide

# After
image

This is inside this project with fixes.

**Comment by MangelMaxime** [comment]
Hello @kant2002 @baronfel,

the changes proposed in this PR are introducing another a bug:

image

Because, the regex used is `(\\**\\))` it means that between **zero** and unlimited number of `*` characters are required before the `)`.

The regex should be `(\\*+\\))` like that we need at least `*)` to detect the end of the comment.

@baronfel You can close this PR and merge PR #169 which includes the changes proposed by @kant2002 and my fix for it.

I couldn't push to @kant2002 branch directly as I am only a contributor and not a maintainer of this repo.

**Comment by baronfel** [comment]
Thanks for the check and the explanation :)

**Pull request closed without merging**
