### PR TITLE
Handle SRTPs in sig files

### PR DESCRIPTION
**Pull request by brianrourkeboll**
- End SRTP matching even when there is no `=` after the `)` of a `(member … : …)`.

This is a bug that you will notice if you look at many signature files in FSharp.Core, [for example](https://github.com/dotnet/fsharp/blob/324ba3dd76e4b7c24cecf838ee0251a12126ca67/src/FSharp.Core/array.fsi#L81-L90).

I tried this out on FSharp.Core, and everything looked good as far as I could tell, but the SRTP patterns are complicated, so I hope this change doesn't break something else.

```fsi
// The highlighting goes awry starting after the "(static member (+): ^T * ^T -> ^T)".
// Notice how the first ^T in "and ^T: (static member Zero: ^T)" is not the right color.
val inline s: array: ^T array -> ^T when ^T: (static member (+): ^T * ^T -> ^T) and ^T: (static member Zero: ^T)

// This is still highlighted wrong.
val p : int

// This comment has two magic characters in it, which fix things:
// )=
val q : int
```

### Before

Screenshot 2024-06-05 174607

### After

Screenshot 2024-06-05 174723

### CODE REVIEW

**Comment by baronfel** [comment]
Very cool! this one is a bit broader in scope though, so I'd appreciate it if @MangelMaxime could take a look and see if he sees anything clearly wrong about it.

**Comment by brianrourkeboll** [comment]
It will be pretty funny if this single-character change fixes this bug that has been bothering me for years and doesn't break anything else 🙃🙃.

**Comment by MangelMaxime** [comment]
Thanks @brianrourkeboll for all the PRs regarding the syntax. 

I will have a look at this PR later today.

But indeed, working with SRTPs is kind of a funny one.

> It will be pretty funny if this single-character change fixes this bug that has been bothering me for years and doesn't break anything else 🙃🙃.

One of the best source of contribution to the grammar seems to be a little bit of frustrating each time you see something off 🤣 I contributed to the grammar for the same reason.

**Comment by MangelMaxime** [comment]
This PR is breaking several syntaxes:

Old on the left - New on the right

CleanShot 2024-06-06 at 16 07 22

CleanShot 2024-06-06 at 16 07 56

CleanShot 2024-06-06 at 16 08 25

To make spotting the diff easier I found this [tool online](https://www.diffchecker.com/image-compare/) which allows you to have a diff map / slider to compare images.

*Black means no changes*

CleanShot 2024-06-06 at 16 09 53

To generate the images, I am using [CodeSnap VSCode extension](https://marketplace.visualstudio.com/items?itemName=adpyke.codesnap)

**Comment by MangelMaxime** [comment]
@brianrourkeboll Yes, if I remember correctly all the `member_declaration` and `common_binding_definition` and `SRTP` thing are a mix of rules which are able to detect more than there normal cases because the scopes are mixed / nested.

There is perhaps a better way of doing it but I am not.

In the past, I had the idea or trying to work from a clean file to perhaps have a different way of doing it but I never found the time to do it as it would be a massive task.

**Comment by brianrourkeboll** [comment]
Hmm, I guess I'll close this for now. As you say, it might take a significant rethinking of things...

**Pull request closed without merging**
