### PR TITLE
Feature/markdown

### PR DESCRIPTION
**Pull request by MangelMaxime**
Before:

capture d ecran 2018-05-25 a 12 55 29

Now:

capture d ecran 2018-05-25 a 12 55 38

### CODE REVIEW

**Comment by matthid** [comment]
nice!

**Comment by Horusiath** [comment]
Looks nice, but maybe comments should be dimmed a little? Having highlighted markdown comments with the same brightness as the code can make actual code harder to read.

**Comment by MangelMaxime** [comment]
@Horusiath I believe this is something that should be done by your theme not by a language grammar.

**Comment by Horusiath** [comment]
Yep, my bad :)

**Pull request merged**
